name: MacRDP

on: 
  workflow_dispatch:

jobs:
  build:
    name: MacRDP
    runs-on: macos-13
    
    steps:
    - name: Enabling Remote Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        curl -s -o start.sh -L "https://raw.githubusercontent.com/efnk001/rdbtest/main/setup.sh"
        chmod +x start.sh
        ./start.sh "$NGROK_AUTH_TOKEN"

    - name: Log In Details To VNC Server
      run: |
        chmod +x login.sh
        ./login.sh

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
